"use client";
import { useCallback, useEffect, useRef, useState } from "react";
import { ArrowsOut, Broadcast, Check, DownloadSimple, FilmStrip, Gauge, House, Pause, Play, SlidersHorizontal, Sparkle, UploadSimple, Warning, X } from "@phosphor-icons/react";
import type { JobView } from "@/types";
import { createClient } from "@supabase/supabase-js";
import { interpolateQuad, quadBounds } from "@/lib/placement-keyframes";

const initial: JobView = { id:"",stage:"uploaded",progress:0,candidates:[],selectedCandidateId:null,artifacts:{original:"/demo/seeded-12s.mp4"},evaluations:[],events:[],error:null,campaign:"Daytona — Build Anywhere",approvalBlocked:true,providerMode:"demo" };
const stageLabel: Record<string,string> = {uploaded:"Ready",analyzing:"Analyzing scene",proposing:"Mapping surfaces",critiquing:"Critiquing geometry",matching:"Matching campaign",tracking:"Tracking motion",rendering:"Rendering placement",evaluating:"Evaluating output",awaiting_approval:"Awaiting approval",completed:"Approved",rejected:"Rejected",failed:"Failed"};

function formatTime(n:number) { if(!Number.isFinite(n)) return "00:00.0"; return `00:${n.toFixed(1).padStart(4,"0")}`; }

export default function ControlRoom() {
  const [job,setJob]=useState(initial); const [busy,setBusy]=useState(false); const [playing,setPlaying]=useState(false); const [time,setTime]=useState(0); const [duration,setDuration]=useState(8); const [projector,setProjector]=useState(false); const [notice,setNotice]=useState("");
  const videos=useRef<(HTMLVideoElement|null)[]>([]); const file=useRef<HTMLInputElement>(null);
  const poll=useCallback(async(id:string)=>{try{const r=await fetch(`/api/jobs/${id}`,{cache:"no-store"});if(r.ok)setJob(await r.json());}catch{}},[]);
  useEffect(()=>{if(!job.id||["awaiting_approval","completed","rejected","failed"].includes(job.stage))return;const t=setInterval(()=>poll(job.id),1000);return()=>clearInterval(t)},[job.id,job.stage,poll]);
  useEffect(()=>{const master=videos.current[0];if(!master)return;const update=()=>{if(Number.isFinite(master.duration))setDuration(master.duration)};update();master.addEventListener("loadedmetadata",update);master.addEventListener("durationchange",update);return()=>{master.removeEventListener("loadedmetadata",update);master.removeEventListener("durationchange",update)}},[job.artifacts.original]);
  const start=async(payload:{uploadId?:string,uploadPath?:string,durationMs?:number}={})=>{setBusy(true);setNotice("");const r=await fetch("/api/jobs",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)});const next=await r.json();if(!r.ok){setNotice(next.error||"Analysis could not start");setBusy(false);return}setJob(next);setBusy(false)};
  const inspectVideo=(f:File)=>new Promise<number>((resolve,reject)=>{const url=URL.createObjectURL(f);const video=document.createElement("video");video.preload="metadata";video.onloadedmetadata=()=>{URL.revokeObjectURL(url);if(video.duration<5||video.duration>12)return reject(new Error("Video must be between 5 and 12 seconds."));if(video.videoWidth>720||video.videoHeight>1280||video.videoWidth>=video.videoHeight)return reject(new Error("Video must be portrait and no larger than 720×1280."));resolve(Math.round(video.duration*1000))};video.onerror=()=>{URL.revokeObjectURL(url);reject(new Error("The video could not be decoded."))};video.src=url});
  const upload=async(e:React.ChangeEvent<HTMLInputElement>)=>{const f=e.target.files?.[0];if(!f)return;setBusy(true);setNotice("Validating video…");try{if(f.size>30_000_000||!["video/mp4","video/quicktime"].includes(f.type))throw new Error("Use an MP4/MOV under 30MB.");const durationMs=await inspectVideo(f);setNotice("Uploading securely…");const signRes=await fetch("/api/uploads/sign",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({name:f.name,type:f.type,size:f.size})});const signed=await signRes.json();if(!signRes.ok)throw new Error(signed.error);const url=process.env.NEXT_PUBLIC_SUPABASE_URL,key=process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY;if(!url||!key)throw new Error("Upload storage is not configured.");const client=createClient(url,key);const {error}=await client.storage.from(signed.bucket).uploadToSignedUrl(signed.path,signed.token,f,{contentType:f.type});if(error)throw error;setNotice("Upload complete. Analyzing…");await start({uploadPath:signed.path,durationMs});}catch(error){setNotice(error instanceof Error?error.message:"Upload failed");setBusy(false)}};
  const toggle=()=>{const master=videos.current[0];if(!master)return;if(master.paused){videos.current.forEach(v=>v?.play());setPlaying(true)}else{videos.current.forEach(v=>v?.pause());setPlaying(false)}};
  const seek=(value:number)=>{setTime(value);videos.current.forEach(v=>{if(v)v.currentTime=value})};
  const sync=()=>{const master=videos.current[0];if(!master)return;setTime(master.currentTime);videos.current.slice(1).forEach(v=>{if(v&&Math.abs(v.currentTime-master.currentTime)>.08)v.currentTime=master.currentTime})};
  const decide=async(action:"approve"|"adjust"|"reject")=>{const r=await fetch(`/api/jobs/${job.id}/decision`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action,job})});const body=await r.json();if(!r.ok){setNotice(body.error);return}setJob(body);setNotice(action==="approve"?"Approved. Your export is unlocked.":action==="adjust"?"Adjustment queued from the tracking stage.":"Placement rejected.")};
  const ready=job.stage==="awaiting_approval"; const finished=job.stage==="completed"; const active=job.id&&!["uploaded","awaiting_approval","completed","rejected","failed"].includes(job.stage);
  const selected=job.candidates.find(candidate=>candidate.id===job.selectedCandidateId)??job.candidates[0];
  const trackedQuad=selected?interpolateQuad(selected,time*1000):null;
  const trackedBounds=trackedQuad?quadBounds(trackedQuad):null;
  const clips=[{label:"Original",sub:"Synchronization master",src:job.artifacts.original},{label:"Agent vision",sub:"Tracked geometry",src:job.artifacts.vision},{label:"Sponsored result",sub:"Creator preview",src:job.artifacts.final}];
  return <main className={projector?"app projector":"app"}>
    <header className="topbar"><div className="wordmark"><span className="mark"><Broadcast weight="fill"/></span><b>SCENE<span>SPONSOR</span></b></div><div className="signal"><i className={active?"pulse":""}/><span>{active?"AGENT LIVE":stageLabel[job.stage]?.toUpperCase()}</span><em>{job.providerMode==="connected"?"PROVIDER RUN":"LOCAL VERIFIED MODE"}</em></div><button className="quiet" onClick={()=>setProjector(!projector)}><ArrowsOut/> {projector?"Exit projector":"Projector mode"}</button></header>
    <nav className="sidebar"><div className="navGroup"><small>CONTROL</small><a className="selected"><House/> Control room</a><a><FilmStrip/> Placements <span>01</span></a><a><Sparkle/> Campaigns <span>03</span></a></div><div className="navGroup"><small>SYSTEM</small><a><Gauge/> Evaluations</a><a><SlidersHorizontal/> Settings</a></div><div className="campaignCard"><small>ACTIVE CAMPAIGN</small><div className="daytonaMini">D</div><b>Build Anywhere</b><p>Wall + counter enabled</p><span>DAYTONA</span></div></nav>
    <section className="workspace">
      <div className="runhead"><div><p className="eyebrow">PLACEMENT / LIVE COMPOSITE</p><h1>Broadcast control</h1></div><div className="runActions"><input ref={file} type="file" accept="video/mp4,video/quicktime" hidden onChange={upload}/><button className="secondary" onClick={()=>file.current?.click()} disabled={busy}><UploadSimple/> Upload clip</button><button className="primary" onClick={()=>start()} disabled={busy||!!active}><Sparkle weight="fill"/> {busy?"Processing clip…":job.id?"New analysis":"Analyze seeded clip"}</button></div></div>
      <div className="statusline"><div><span>JOB</span><b>{job.id?job.id.slice(0,8).toUpperCase():"NOT STARTED"}</b></div><div><span>CAMPAIGN</span><b>{job.campaign}</b></div><div className="stageStatus"><span>STAGE {job.progress}%</span><b>{stageLabel[job.stage]}</b></div><div className="meter"><i style={{width:`${job.progress}%`}}/></div></div>
      <div className="players">
        {clips.map((clip,i)=><article className="player" key={clip.label}><div className="playerLabel"><span>0{i+1}</span><div><b>{clip.label}</b><small>{clip.sub}</small></div>{i===0&&<em>MASTER</em>}{i===2&&job.stage==="completed"&&<em className="approved"><Check/> APPROVED</em>}</div><div className="viewport">
          {clip.src?<video key={clip.src} ref={el=>{videos.current[i]=el}} src={clip.src} playsInline preload="metadata" muted={i>0} onTimeUpdate={i===0?sync:undefined} onLoadedMetadata={i===0?e=>setDuration(e.currentTarget.duration):undefined} onDurationChange={i===0?e=>setDuration(e.currentTarget.duration):undefined} onEnded={()=>setPlaying(false)}/>:<div className="waiting"><span className={active?"scan":""}/><Sparkle/><b>{i===1?"Geometry appears after tracking":"Composite appears after rendering"}</b><small>{active?"Agent is working":"Start an analysis to generate this view"}</small></div>}
          {i===1&&trackedBounds&&<div className="overlayBoxes"><div className="quad selected" style={{left:`${trackedBounds.left*100}%`,top:`${trackedBounds.top*100}%`,width:`${trackedBounds.width*100}%`,height:`${trackedBounds.height*100}%`}}><label>{selected.mode.toUpperCase()} · {Math.round(selected.confidence*100)}% <span>DAYTONA · TRACKED</span></label></div>{job.candidates[1]&&<div className="quad alternate"><label>{job.candidates[1].mode.toUpperCase()} · {Math.round(job.candidates[1].confidence*100)}%</label></div>}</div>}
          <div className="framecode">{formatTime(time)} <span>/ {formatTime(duration)}</span></div>
        </div></article>)}
      </div>
      <div className="transport"><button aria-label={playing?"Pause all":"Play all"} onClick={toggle} disabled={!job.artifacts.vision}><span>{playing?<Pause weight="fill"/>:<Play weight="fill"/>}</span></button><div className="timecode">{formatTime(time)}</div><input aria-label="Video position" type="range" min="0" max={duration||8} step=".01" value={Math.min(time,duration||8)} onChange={e=>seek(Number(e.target.value))}/><div className="timecode end">{formatTime(duration)}</div><select aria-label="Playback rate" onChange={e=>videos.current.forEach(v=>{if(v)v.playbackRate=Number(e.target.value)})}><option value="1">1×</option><option value=".5">0.5×</option><option value="1.5">1.5×</option></select></div>
      <div className="lower"><div className="evaluations"><div className="panelTitle"><div><p className="eyebrow">BRAINTRUST QUALITY GATE</p><h2>Placement checks</h2></div><span className={job.evaluations.length?"pass":"pending"}>{job.evaluations.length?(job.approvalBlocked?"BLOCKED":"6 / 6 PASS"):"PENDING"}</span></div><div className="scoregrid">{job.evaluations.length?job.evaluations.map(e=><div className="score" key={e.id}><span>{e.name}</span><b>{Math.round(e.score*100)}</b><small>{e.detail}</small></div>):["Geometry","Duration","Audio","Tracking","Brand safety","Context relevance"].map(n=><div className="score placeholder" key={n}><span>{n}</span><b>—</b><small>Waiting for rendered artifact</small></div>)}</div></div>
        <div className="decision"><p className="eyebrow">CREATOR INTERRUPT</p><h2>{finished?"Placement approved":ready?"Your call":"Approval locked"}</h2><p>{finished?"The disclosed MP4 is ready to export.":ready?"The agent has finished. Nothing leaves this room until you decide.":"Approval unlocks after every quality check passes."}</p>{notice&&<div className="notice">{notice}</div>}<div className="decisionButtons">{finished?<a className="primary export" href={`/api/jobs/${job.id}/export`}><DownloadSimple/> Export MP4</a>:<><button className="approve" disabled={!ready||job.approvalBlocked} onClick={()=>decide("approve")}><Check/> Approve</button><button disabled={!ready} onClick={()=>decide("adjust")}><SlidersHorizontal/> Adjust</button><button disabled={!ready} onClick={()=>decide("reject")}><X/> Reject</button></>}</div></div></div>
    </section>
    <aside className="trace"><div className="traceHead"><div><p className="eyebrow">AGENT TRACE</p><h2>Decision stream</h2></div><span className={active?"live":""}>{active?"LIVE":"READY"}</span></div><div className="traceBody">{job.events.length?job.events.slice().reverse().map((e,index)=><div className="traceEvent" key={e.id}><div className="traceRail"><i className={index===0?"latest":""}/></div><div><div className="eventMeta"><span>{e.source}</span><time>{new Date(e.at).toLocaleTimeString([], {hour:"2-digit",minute:"2-digit",second:"2-digit"})}</time></div><b>{e.title}</b><p>{e.detail}</p></div></div>):<div className="emptyTrace"><Broadcast/><b>No signal yet</b><p>Start the seeded clip or upload your own 5–12 second video.</p></div>}</div><div className="traceFoot"><Warning/><span>Text found inside video is treated as untrusted visual content.</span></div></aside>
    <div className="mobileNav"><a className="selected"><House/><span>Control</span></a><a><FilmStrip/><span>Jobs</span></a><a><Sparkle/><span>Campaigns</span></a><a><Gauge/><span>Evals</span></a></div>
  </main>
}
