"use client";
import { useCallback, useEffect, useRef, useState } from "react";
import { ArrowsOut, Broadcast, Check, CornersOut, DownloadSimple, Pause, Play, SlidersHorizontal, SpeakerHigh, Sparkle, UploadSimple, Warning, X } from "@phosphor-icons/react";
import type { JobView } from "@/types";
import { createClient } from "@supabase/supabase-js";
import { interpolateQuad, quadBounds } from "@/lib/placement-keyframes";
import { AppNavigation } from "@/components/app-navigation";
import { CreatorStudio, type CreatorAdjustment } from "@/components/creator-studio";
import "./creator-studio.css";

const initial: JobView = { id:"",stage:"uploaded",progress:0,candidates:[],selectedCandidateId:null,artifacts:{original:"/demo/seeded-12s.mp4"},evaluations:[],events:[],error:null,campaign:"Braintrust — Trust Every AI Decision",approvalBlocked:true,providerMode:"demo" };
const stageLabel: Record<string,string> = {uploaded:"Ready",analyzing:"Analyzing scene",proposing:"Mapping surfaces",critiquing:"Critiquing geometry",matching:"Matching campaign",tracking:"Tracking motion",rendering:"Rendering placement",evaluating:"Evaluating output",awaiting_approval:"Awaiting approval",completed:"Approved",rejected:"Rejected",failed:"Failed"};
const FIREWORKS_SETTING = "scenesponsor:fireworks-enabled";

function formatTime(n:number) { if(!Number.isFinite(n)) return "00:00.0"; return `00:${n.toFixed(1).padStart(4,"0")}`; }

export default function ControlRoom() {
  const [job,setJob]=useState(initial); const [busy,setBusy]=useState(false); const [playing,setPlaying]=useState(false); const [time,setTime]=useState(0); const [duration,setDuration]=useState(12); const [projector,setProjector]=useState(false); const [notice,setNotice]=useState(""); const [fireworksEnabled,setFireworksEnabled]=useState(true);
  const [activeClip,setActiveClip]=useState(0); const [sequenceRunning,setSequenceRunning]=useState(false); const [readyClips,setReadyClips]=useState([false,false,false]); const [clipTimes,setClipTimes]=useState([0,0,0]); const [rate,setRate]=useState(1); const [volume,setVolume]=useState(1); const [decisionBusy,setDecisionBusy]=useState(false);
  const videos=useRef<(HTMLVideoElement|null)[]>([]); const file=useRef<HTMLInputElement>(null); const players=useRef<HTMLDivElement>(null);
  const poll=useCallback(async(id:string)=>{try{const r=await fetch(`/api/jobs/${id}`,{cache:"no-store"});if(r.ok)setJob(await r.json());}catch{}},[]);
  useEffect(()=>{const sync=()=>setFireworksEnabled(localStorage.getItem(FIREWORKS_SETTING)!=="false");sync();window.addEventListener("storage",sync);return()=>window.removeEventListener("storage",sync)},[]);
  useEffect(()=>{const id=new URLSearchParams(window.location.search).get("job");if(id)void poll(id)},[poll]);
  useEffect(()=>{if(!job.id||["awaiting_approval","completed","rejected","failed"].includes(job.stage))return;const t=setInterval(()=>poll(job.id),1000);return()=>clearInterval(t)},[job.id,job.stage,poll]);
  useEffect(()=>{const master=videos.current[0];if(!master)return;const update=()=>{if(Number.isFinite(master.duration))setDuration(master.duration)};update();master.addEventListener("loadedmetadata",update);master.addEventListener("durationchange",update);return()=>{master.removeEventListener("loadedmetadata",update);master.removeEventListener("durationchange",update)}},[job.artifacts.original]);
  useEffect(()=>{videos.current.forEach(video=>video?.pause());setActiveClip(0);setTime(0);setClipTimes([0,0,0]);setReadyClips([false,false,false]);setPlaying(false)},[job.artifacts.original]);
  const start=async(payload:{uploadId?:string,uploadPath?:string,durationMs?:number}={})=>{const uploaded=!!payload.uploadPath;videos.current.forEach(video=>{if(video){video.pause();video.currentTime=0}});setActiveClip(0);setTime(0);setClipTimes([0,0,0]);setReadyClips([false,false,false]);setPlaying(false);setSequenceRunning(!uploaded);setBusy(true);setNotice(!fireworksEnabled?"":uploaded?"Upload secured. Waiting for the uploaded Original to buffer…":"Playing Original while Agent Vision and Sponsored Result render…");if(!uploaded){const master=videos.current[0];if(master)void master.play().then(()=>setPlaying(true)).catch(()=>undefined)}try{const r=await fetch("/api/jobs",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({...payload,forceFallback:!fireworksEnabled})});const next=await r.json();if(!r.ok)throw new Error(next.error||"Analysis could not start");setJob(next);if(uploaded)setSequenceRunning(true)}catch(error){setNotice(error instanceof Error?error.message:"Analysis could not start");setSequenceRunning(false)}finally{setBusy(false)}};
  const inspectVideo=(f:File)=>new Promise<number>((resolve,reject)=>{const url=URL.createObjectURL(f);const video=document.createElement("video");video.preload="metadata";video.onloadedmetadata=()=>{URL.revokeObjectURL(url);if(video.duration<5||video.duration>12)return reject(new Error("Video must be between 5 and 12 seconds."));if(video.videoWidth>720||video.videoHeight>1280||video.videoWidth>=video.videoHeight)return reject(new Error("Video must be portrait and no larger than 720×1280."));resolve(Math.round(video.duration*1000))};video.onerror=()=>{URL.revokeObjectURL(url);reject(new Error("The video could not be decoded."))};video.src=url});
  const upload=async(e:React.ChangeEvent<HTMLInputElement>)=>{const input=e.target;const f=input.files?.[0];if(!f)return;setBusy(true);setNotice("Validating video…");try{if(f.size>30_000_000||!["video/mp4","video/quicktime"].includes(f.type))throw new Error("Use an MP4/MOV under 30MB.");const durationMs=await inspectVideo(f);setNotice("Uploading securely…");const signRes=await fetch("/api/uploads/sign",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({name:f.name,type:f.type,size:f.size})});const signed=await signRes.json();if(!signRes.ok)throw new Error(signed.error);const url=process.env.NEXT_PUBLIC_SUPABASE_URL,key=process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY;if(!url||!key)throw new Error("Upload storage is not configured.");const client=createClient(url,key);const {error}=await client.storage.from(signed.bucket).uploadToSignedUrl(signed.path,signed.token,f,{contentType:f.type});if(error)throw error;setNotice("Upload complete. Analyzing…");await start({uploadPath:signed.path,durationMs})}catch(error){setNotice(error instanceof Error?error.message:"Upload failed");setBusy(false)}finally{input.value=""}};
  const toggle=()=>{const current=videos.current[activeClip];if(playing){videos.current.forEach(video=>video?.pause());setPlaying(false);setSequenceRunning(false);return}if(current?.ended&&activeClip<2){const next=activeClip+1;const nextSource=next===1?job.artifacts.vision:job.artifacts.final;if(nextSource){setReadyClips(values=>values.map((value,index)=>index===next?false:value));setClipTimes(values=>values.map((value,index)=>index===next?0:value));setActiveClip(next);setTime(0);setSequenceRunning(true);setNotice(`Loading ${next===1?"Agent Vision":"Sponsored Result"} now…`);return}}if(activeClip===2&&current?.ended){videos.current.forEach(video=>{if(video){video.pause();video.currentTime=0}});setActiveClip(0);setTime(0);setClipTimes([0,0,0]);setReadyClips([false,false,false]);setSequenceRunning(true);const original=videos.current[0];if(original&&original.readyState>=3)void original.play().then(()=>{setPlaying(true);setNotice("Sequence restarted from Original.")}).catch(()=>setNotice("Playback was blocked. Press play again."));return}setSequenceRunning(true);if(current&&current.readyState>=3)void current.play().then(()=>setPlaying(true)).catch(()=>setNotice("Playback was blocked. Press play again."))};
  const seek=(value:number)=>{setTime(value);setClipTimes(current=>current.map((item,i)=>i===activeClip?value:item));const current=videos.current[activeClip];if(current)current.currentTime=value};
  const onClipTime=(index:number,value:number)=>{setClipTimes(current=>current.map((item,i)=>i===index?value:item));if(index===activeClip)setTime(value)};
  const onClipEnded=(index:number)=>{if(index!==activeClip)return;setPlaying(false);if(sequenceRunning&&index<2){const next=index+1;if(!clips[next]?.src){setSequenceRunning(false);setNotice(`${clips[next].label} is not ready yet.`);return}setReadyClips(current=>current.map((value,i)=>i===next?false:value));setClipTimes(current=>current.map((value,i)=>i===next?0:value));setActiveClip(next);setTime(0);setNotice(index===0?"Original complete. Loading Agent Vision now…":"Agent Vision complete. Loading Sponsored Result now…")}else{setSequenceRunning(false);setNotice("Full three-clip sequence complete.")}};
  const fullscreen=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await players.current?.requestFullscreen()}catch{setNotice("Fullscreen is unavailable in this browser.")}};
  const decide=async(action:"approve"|"adjust"|"reject")=>{setDecisionBusy(true);try{const r=await fetch(`/api/jobs/${job.id}/decision`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action,job})});const body=await r.json();if(!r.ok)throw new Error(body.error||"Decision failed");setJob(body);setNotice(action==="approve"?"Approved. Your export is unlocked.":action==="adjust"?"Rerender queued from the tracking stage.":"Placement rejected.")}catch(error){setNotice(error instanceof Error?error.message:"Decision failed")}finally{setDecisionBusy(false)}};
  const adjustComposite=async(adjustment:CreatorAdjustment)=>{setDecisionBusy(true);try{const r=await fetch(`/api/jobs/${job.id}/adjustment`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(adjustment)});const body=await r.json();if(!r.ok)throw new Error(body.error||"Adjustment failed");setJob(body);setNotice(`Creator adjustment queued: ${adjustment.instruction}`)}catch(error){setNotice(error instanceof Error?error.message:"Adjustment failed");throw error}finally{setDecisionBusy(false)}};
  const retry=async()=>{setBusy(true);videos.current.forEach(video=>{if(video){video.pause();video.currentTime=0}});setActiveClip(0);setTime(0);setClipTimes([0,0,0]);setPlaying(false);try{const r=await fetch(`/api/jobs/${job.id}/retry`,{method:"POST"});const body=await r.json();if(!r.ok)throw new Error(body.error||"Retry failed");setJob(body);setSequenceRunning(true);setNotice("Retry started from the same source clip.")}catch(error){setSequenceRunning(false);setNotice(error instanceof Error?error.message:"Retry failed")}finally{setBusy(false)}};
  const ready=job.stage==="awaiting_approval"; const finished=job.stage==="completed"; const active=job.id&&!["uploaded","awaiting_approval","completed","rejected","failed"].includes(job.stage);
  const selected=job.candidates.find(candidate=>candidate.id===job.selectedCandidateId)??job.candidates[0];
  const visionOverlays=job.candidates.map(candidate=>{const quad=interpolateQuad(candidate,clipTimes[1]*1000);return quad?{candidate,bounds:quadBounds(quad)}:null}).filter((item):item is NonNullable<typeof item>=>item!==null);
  const clips=[{label:"Original",sub:"Synchronization master",src:job.artifacts.original},{label:"Agent vision",sub:"Tracked geometry",src:job.artifacts.vision},{label:"Sponsored result",sub:"Creator preview",src:job.artifacts.final}];
  const activeSource=clips[activeClip]?.src; const activeReady=!!activeSource&&readyClips[activeClip];
  useEffect(()=>{setReadyClips(values=>values[1]?values.map((value,index)=>index===1?false:value):values)},[job.artifacts.vision]);
  useEffect(()=>{setReadyClips(values=>values[2]?values.map((value,index)=>index===2?false:value):values)},[job.artifacts.final]);
  useEffect(()=>{if(sequenceRunning||playing||activeClip>=2)return;const current=videos.current[activeClip];const next=activeClip+1;const nextSource=clips[next]?.src;if(!current?.ended||!nextSource)return;setReadyClips(values=>values.map((value,index)=>index===next?false:value));setClipTimes(values=>values.map((value,index)=>index===next?0:value));setActiveClip(next);setTime(0);setSequenceRunning(true);setNotice(`${clips[next].label} is ready. Loading it now…`)},[activeClip,playing,sequenceRunning,job.stage,job.artifacts.vision,job.artifacts.final]);
  useEffect(()=>{videos.current.forEach((video,i)=>{if(video){video.muted=i!==activeClip;video.volume=volume;video.playbackRate=rate}})},[activeClip,rate,volume,job.artifacts.vision,job.artifacts.final]);
  useEffect(()=>{if(!sequenceRunning||playing||!activeReady)return;const current=videos.current[activeClip];if(!current||current.readyState<3)return;void current.play().then(()=>{setPlaying(true);setNotice(activeClip===0?"Original playing.":activeClip===1?"Agent Vision playing.":"Sponsored Result playing.")}).catch(()=>{setSequenceRunning(false);setNotice("Playback was blocked. Press play to continue.")})},[activeClip,activeSource,activeReady,playing,sequenceRunning]);
  return <main className={projector?"app projector":"app"}>
    <header className="topbar"><div className="wordmark"><span className="mark"><Broadcast weight="fill"/></span><b>SCENE<span>SPONSOR</span></b></div><div className="signal"><i className={active?"pulse":""}/><span>{active?"AGENT LIVE":stageLabel[job.stage]?.toUpperCase()}</span><em>{job.providerMode==="connected"?"PROVIDER RUN":"LOCAL VERIFIED MODE"}</em></div><button className="quiet" onClick={()=>setProjector(!projector)}><ArrowsOut/> {projector?"Exit projector":"Projector mode"}</button></header>
    <AppNavigation/>
    <section className="workspace" id="control">
      <div className="runhead"><div><p className="eyebrow">PLACEMENT / LIVE COMPOSITE</p><h1>Broadcast control</h1></div><div className="runActions"><input ref={file} type="file" accept="video/mp4,video/quicktime" hidden onChange={upload}/><button className="secondary" onClick={()=>file.current?.click()} disabled={busy}><UploadSimple/> Upload clip</button><button className="primary" onClick={()=>start()} disabled={busy||!!active}><Sparkle weight="fill"/> {busy?"Processing clip…":job.id?"New analysis":"Analyze clip"}</button></div></div>
      <div className="statusline" id="campaigns"><div><span>JOB</span><b>{job.id?job.id.slice(0,8).toUpperCase():"NOT STARTED"}</b></div><div><span>CAMPAIGN</span><b>{job.campaign}</b></div><div className="stageStatus"><span>STAGE {job.progress}%</span><b>{stageLabel[job.stage]}</b></div><div className="meter"><i style={{width:`${job.progress}%`}}/></div></div>
      <div className="players" id="placements" ref={players}>
        {clips.map((clip,i)=>{const loadedSrc=i<=activeClip?clip.src:undefined;const clipReady=!!loadedSrc&&readyClips[i];const markReady=()=>setReadyClips(current=>current[i]?current:current.map((value,index)=>index===i?true:value));return <article className={`player ${activeClip===i?"activeClip":""} ${loadedSrc&&!clipReady?"buffering":""}`} key={clip.label}><div className="playerLabel"><span>0{i+1}</span><div><b>{clip.label}</b><small>{clip.sub}</small></div>{activeClip===i&&<em className={clipReady?"approved":""}>{playing?"PLAYING":clipReady?"READY":"BUFFERING"}</em>}{i===2&&job.stage==="completed"&&<em className="approved"><Check/> APPROVED</em>}</div><div className="viewport">
          {loadedSrc?<video key={`${i}-${loadedSrc}`} ref={el=>{videos.current[i]=el;if(el){el.playbackRate=rate;el.volume=volume;if(el.readyState>=3)queueMicrotask(markReady)}}} src={loadedSrc} playsInline preload="auto" muted={i!==activeClip} onTimeUpdate={e=>onClipTime(i,e.currentTarget.currentTime)} onLoadedMetadata={e=>{e.currentTarget.playbackRate=rate;if(i===activeClip)setDuration(e.currentTarget.duration)}} onDurationChange={e=>{if(i===activeClip)setDuration(e.currentTarget.duration)}} onCanPlay={markReady} onEnded={()=>onClipEnded(i)} onError={()=>setNotice(`${clip.label} could not be decoded. Retry the analysis.`)}/>:<div className="waiting"><Sparkle/><b>{i>activeClip?"Waiting for previous clip to finish":i===1?"Geometry appears after tracking":"Composite appears after rendering"}</b><small>{i>activeClip?"This video has not loaded yet":active?"Agent is working":"Start an analysis to generate this view"}</small></div>}
          {i===1&&activeClip===1&&visionOverlays.length>0&&<div className="overlayBoxes">{visionOverlays.map(({candidate,bounds})=><div key={candidate.id} className={`quad ${candidate.id===selected?.id?"selected":"alternate"}`} style={{left:`${bounds.left*100}%`,top:`${bounds.top*100}%`,width:`${bounds.width*100}%`,height:`${bounds.height*100}%`,transform:"none"}}><label>{candidate.mode.toUpperCase()} · {Math.round(candidate.confidence*100)}% {candidate.id===selected?.id&&<span>FIREWORKS · KEYFRAMED</span>}</label></div>)}</div>}
          <div className="framecode">{formatTime(clipTimes[i])} <span>/ {formatTime(duration)}</span></div>
        </div></article>})}
      </div>
      <div className="transport" id="settings"><button aria-label={playing?"Pause sequence":"Play sequence"} onClick={toggle} disabled={!clips[activeClip]?.src||(!activeReady&&activeClip>0)}><span>{playing?<Pause weight="fill"/>:<Play weight="fill"/>}</span></button><div className="timecode">0{activeClip+1} · {formatTime(time)}</div><input aria-label="Video position" type="range" min="0" max={duration||12} step=".01" value={Math.min(time,duration||12)} onChange={e=>seek(Number(e.target.value))}/><div className="timecode end">{formatTime(duration)}</div><SpeakerHigh/><input aria-label="Volume" style={{maxWidth:80}} type="range" min="0" max="1" step=".05" value={volume} onChange={e=>setVolume(Number(e.target.value))}/><select aria-label="Playback rate" value={rate} onChange={e=>setRate(Number(e.target.value))}><option value="1">1×</option><option value=".5">0.5×</option><option value="1.5">1.5×</option></select><button className="transportAction" aria-label="Fullscreen players" onClick={fullscreen}><CornersOut/></button></div>
      <div className="lower"><div className="evaluations" id="evaluations"><div className="panelTitle"><div><p className="eyebrow">BRAINTRUST QUALITY GATE</p><h2>Placement checks</h2></div><span className={job.evaluations.length?"pass":"pending"}>{job.evaluations.length?(job.approvalBlocked?"BLOCKED":"6 / 6 PASS"):"PENDING"}</span></div><div className="scoregrid">{job.evaluations.length?job.evaluations.map(e=><div className="score" key={e.id}><span>{e.name}</span><b>{Math.round(e.score*100)}</b><small>{e.detail}</small></div>):["Geometry","Duration","Audio","Tracking","Brand safety","Context relevance"].map(n=><div className="score placeholder" key={n}><span>{n}</span><b>—</b><small>Waiting for rendered artifact</small></div>)}</div></div>
        <div className="decision" id="creator"><p className="eyebrow">CREATOR INTERRUPT</p><h2>{finished?"Placement approved":ready?"Your call":"Approval locked"}</h2><p>{finished?"The disclosed MP4 is ready to export.":ready?"The agent has finished. Nothing leaves this room until you decide.":"Approval unlocks after every quality check passes."}</p>{notice&&<div className="notice">{notice}</div>}<div className="decisionButtons">{finished?<a className="primary export" href={`/api/jobs/${job.id}/export`}><DownloadSimple/> Export MP4</a>:job.stage==="failed"?<button className="approve" disabled={busy} onClick={retry}><Sparkle/> Retry analysis</button>:<><button className="approve" disabled={!ready||job.approvalBlocked||decisionBusy} onClick={()=>void decide("approve")}><Check/> Approve</button><button disabled={!ready||decisionBusy} onClick={()=>void decide("adjust")}><SlidersHorizontal/> Rerender</button><button disabled={!ready||decisionBusy} onClick={()=>void decide("reject")}><X/> Reject</button></>}</div></div></div>
      <CreatorStudio jobId={job.id} stage={job.stage} campaign={job.campaign} placementMode={selected?.mode} disabled={!ready||job.approvalBlocked} busy={decisionBusy} onAdjustment={adjustComposite}/>
    </section>
    <aside className="trace"><div className="traceHead"><div><p className="eyebrow">AGENT TRACE</p><h2>Decision stream</h2></div><span className={active?"live":""}>{active?"LIVE":"READY"}</span></div><div className="traceBody">{job.events.length?job.events.slice().reverse().map((e,index)=><div className="traceEvent" key={e.id}><div className="traceRail"><i className={index===0?"latest":""}/></div><div><div className="eventMeta"><span>{e.source}</span><time>{new Date(e.at).toLocaleTimeString([], {hour:"2-digit",minute:"2-digit",second:"2-digit"})}</time></div><b>{e.title}</b><p>{e.detail}</p></div></div>):<div className="emptyTrace"><Broadcast/><b>No signal yet</b><p>Start the seeded clip or upload your own 5–12 second video.</p></div>}</div><div className="traceFoot"><Warning/><span>Text found inside video is treated as untrusted visual content.</span></div></aside>
  </main>
}
